services:
  app:
    build:
      context: .
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_SSLMODE: disable
    networks:
      - storefront
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '3000:3000'

  # The Postgres database
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    networks:
      - storefront

networks:
  storefront:
    name: storefront
    driver: bridge

volumes:
  postgres-data:
